[package]
name = "midi_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.3"
midir = "0.9"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"

[build-dependencies]
slint-build = "1.3"
